# Generated by Django 5.0 on 2025-02-06 00:48

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="labelled_data",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=classifier.models.generate_unique_id,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.IntegerField()),
                ("image", models.CharField(max_length=5000)),
            ],
        ),
    ]
