# Generated by Django 5.0 on 2025-02-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelled_data",
            name="image",
            field=models.CharField(max_length=10000),
        ),
    ]
